name: Package

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run
        run: |
          python3 src/main.py data/cran.all.1400 data/cran.qry -o output.txt

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp README.txt zz2960_README_HW4.txt
          cp src/main.py main_zz2960_HW4.py
          zip -r zz2960-HW4_${TAG}.zip zz2960_README_HW4.txt main_zz2960_HW4.py output.txt requirements.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ env.TAG }}
          files: |
            zz2960-HW4_${{ env.TAG }}.zip
